# Курс Фреймворк PyTorch для разработки искусственных нейронных сетей

# Практическое задание урока 1. Введение в PyTorch

In [157]:
import torch

In [158]:
import numpy as np

In [159]:
# Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5).type(torch.float32)
print("x :\n%s\n" % x)

x :
tensor([[[-2.1095,  0.4776, -2.0944, -0.8705,  0.6125],
         [-0.7013,  0.2828, -1.0101,  0.0872, -0.5349],
         [ 0.8543,  0.4306, -0.3374,  0.4346,  0.5843],
         [-0.9306, -1.6217, -0.4608,  0.0243,  0.2502]],

        [[-0.1399, -0.6379,  1.0704,  0.0701, -2.4895],
         [-0.4167, -1.1401, -0.5101, -0.7422,  0.4644],
         [ 0.0124, -0.5860,  0.7514,  0.2826,  1.2579],
         [-0.7056,  0.9809,  0.0971, -0.0794, -1.1539]],

        [[-0.2929,  0.8558,  0.5299, -1.1276,  0.9842],
         [-0.5934, -1.3192,  0.9597,  0.6766, -1.5860],
         [ 1.0044,  1.0818, -0.2662, -0.0125,  0.6804],
         [ 0.0349,  1.1729,  0.3240, -0.3972,  0.6421]]])



In [160]:
# Выведите его форму (shape)

print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([3, 4, 5])



In [161]:
# Приведите его к форме 6 X 10

x.resize_(6, 10)
print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([6, 10])



In [162]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [163]:
x.resize_(3, 4, 5)
print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([3, 4, 5])



In [164]:
vec = torch.FloatTensor([1, 4, 2, 2, 1])

In [165]:
x * vec

tensor([[[-2.1095,  1.9103, -4.1888, -1.7411,  0.6125],
         [-0.7013,  1.1311, -2.0203,  0.1743, -0.5349],
         [ 0.8543,  1.7223, -0.6748,  0.8693,  0.5843],
         [-0.9306, -6.4869, -0.9216,  0.0487,  0.2502]],

        [[-0.1399, -2.5516,  2.1408,  0.1401, -2.4895],
         [-0.4167, -4.5605, -1.0202, -1.4844,  0.4644],
         [ 0.0124, -2.3441,  1.5028,  0.5653,  1.2579],
         [-0.7056,  3.9237,  0.1941, -0.1587, -1.1539]],

        [[-0.2929,  3.4233,  1.0599, -2.2551,  0.9842],
         [-0.5934, -5.2770,  1.9194,  1.3532, -1.5860],
         [ 1.0044,  4.3270, -0.5323, -0.0250,  0.6804],
         [ 0.0349,  4.6915,  0.6480, -0.7943,  0.6421]]])

In [166]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [167]:
x.resize_(6, 10)
torch.matmul(x, x.transpose(0,1)).size()

torch.Size([6, 6])

In [168]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [169]:
from torch.autograd import Variable

In [170]:
x = Variable(torch.FloatTensor([1, 0.5, 2]), requires_grad = True)
z = Variable(torch.ones(3), requires_grad = True)
t = Variable(torch.ones(3), requires_grad = True)

In [171]:
y = x**3 + z - 75*t
print_tens_info(y)

X :
tensor([-73.0000, -73.8750, -66.0000], grad_fn=<SubBackward0>)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor



In [172]:
y.backward(torch.ones(3))

In [173]:
print("Производная в точке x = (1, 0.5, 2) : %s\n" % (x.grad))

Производная в точке x = (1, 0.5, 2) : tensor([ 3.0000,  0.7500, 12.0000])



In [174]:
# Создайте единичный тензор размера 5x6

x = torch.ones(5,6)
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))

X :
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

X размеры : torch.Size([5, 6])

X тип : <class 'torch.Tensor'>



In [175]:
# Переведите его в формат numpy

x = x.numpy()
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))

X :
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

X размеры : (5, 6)

X тип : <class 'numpy.ndarray'>



In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

В последней части лекции выполнена SGD оптимизация модели в виде одного линейного слоя. Как сделать аналочно с более привычными функциями не разобралась самостоятельно.