# Курс Фреймворк PyTorch для разработки искусственных нейронных сетей

# Практическое задание урока 1. Введение в PyTorch

In [22]:
import torch

In [23]:
import numpy as np

In [24]:
# Создайте случайный FloatTensor размера 3x4x5

x = torch.randn(3, 4, 5).type(torch.float32)
print("x :\n%s\n" % x)

x :
tensor([[[ 0.5353,  0.8441,  0.8003, -1.1127,  0.9933],
         [-1.6488, -0.2480,  0.3908,  2.5197,  1.1757],
         [-0.2168,  0.2910,  0.8514,  0.7223,  1.6678],
         [-0.7811, -0.0477,  0.1446,  0.7996,  0.4342]],

        [[ 0.3505, -0.1252,  0.3387, -0.7717,  0.5251],
         [ 1.6172,  1.4541,  0.4938, -0.5010, -1.5116],
         [ 0.1850, -1.2500,  0.3068, -1.4704, -0.7595],
         [ 0.1701, -1.9152, -0.0799,  1.0843, -0.2786]],

        [[-0.9652,  0.4058,  0.5904,  0.8136,  0.9287],
         [ 0.3432,  0.3833, -2.1439, -0.1234, -1.8137],
         [-0.8563, -0.3157,  0.8019,  0.0315,  1.8382],
         [ 0.3362,  0.9695, -0.4409,  0.3742, -1.6371]]])



In [25]:
# Выведите его форму (shape)

print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([3, 4, 5])



In [26]:
# Приведите его к форме 6 X 10

x.resize_(6, 10)
print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([6, 10])



In [27]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [28]:
x.resize_(3, 4, 5)
print("x размеры : %s\n" % (x.shape,))

x размеры : torch.Size([3, 4, 5])



In [29]:
vec = torch.FloatTensor([1, 4, 2, 2, 1])

In [30]:
x * vec

tensor([[[ 0.5353,  3.3764,  1.6005, -2.2253,  0.9933],
         [-1.6488, -0.9919,  0.7816,  5.0394,  1.1757],
         [-0.2168,  1.1638,  1.7029,  1.4446,  1.6678],
         [-0.7811, -0.1907,  0.2892,  1.5992,  0.4342]],

        [[ 0.3505, -0.5007,  0.6775, -1.5434,  0.5251],
         [ 1.6172,  5.8162,  0.9876, -1.0019, -1.5116],
         [ 0.1850, -4.9999,  0.6135, -2.9408, -0.7595],
         [ 0.1701, -7.6607, -0.1598,  2.1685, -0.2786]],

        [[-0.9652,  1.6231,  1.1807,  1.6271,  0.9287],
         [ 0.3432,  1.5332, -4.2877, -0.2469, -1.8137],
         [-0.8563, -1.2627,  1.6038,  0.0629,  1.8382],
         [ 0.3362,  3.8781, -0.8818,  0.7484, -1.6371]]])

In [31]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [32]:
x.resize_(6, 10)
torch.matmul(x, x.transpose(0,1)).size()

torch.Size([6, 6])

In [33]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [34]:
from torch.autograd import Variable

In [35]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))
#    print("Добавим 10 :\n%s\n" % (tensor + 10))
#     print("Среднее по строчке :\n%s\n" % (tensor.mean(axis=-1)))
#     print("Среднее по столбцу :\n%s\n" % (tensor.mean(axis=0)))

In [36]:
x = Variable(torch.FloatTensor([1, 0.5, 2]), requires_grad = True)
z = Variable(torch.ones(3), requires_grad = True)
t = Variable(torch.ones(3), requires_grad = True)

In [37]:
y = x**3 + z - 75*t
print_tens_info(y)

X :
tensor([-73.0000, -73.8750, -66.0000], grad_fn=<SubBackward0>)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor



In [38]:
y.backward(torch.ones(3))

In [39]:
print("Производная в точке x = (1, 0.5, 2) : %s\n" % (x.grad))

Производная в точке x = (1, 0.5, 2) : tensor([ 3.0000,  0.7500, 12.0000])



In [40]:
# Создайте единичный тензор размера 5x6

x = torch.ones(5,6)
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))

X :
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

X размеры : torch.Size([5, 6])

X тип : <class 'torch.Tensor'>



In [41]:
# Переведите его в формат numpy

x = x.numpy()
print("X :\n%s\n" % x)
print("X размеры : %s\n" % (x.shape,))
print("X тип : %s\n" % (type(x)))

X :
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

X размеры : (5, 6)

X тип : <class 'numpy.ndarray'>



In [42]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

#### Вариант первый (один шаг оптимизации)

In [43]:
# importing libraries
from torch import nn 
from torch import optim

In [190]:
x_data = Variable(torch.tensor([[2.0]]))
y_data = Variable(torch.tensor([[12.0]]))
w1 = Variable(torch.randn(1), requires_grad = True) #  creating random tensors for weights

In [191]:
def forward(x):
  y = x**w1 - 2 * x**2 + 5
  return y

In [192]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD([w1], lr=0.001)

In [193]:
optimizer.zero_grad()
y_pred = forward(x_data)
loss = criterion(y_pred, y_data)
print('loss: ', loss.item())
print ('dY/dw1: ', w1.grad) 

loss:  190.30955505371094
dY/dw1:  None


In [194]:
loss.backward()
print ('dY/dw1: ', w1.grad)
print ('w1: ', w1)

dY/dw1:  tensor([-23.0396])
w1:  tensor([0.2687], requires_grad=True)


In [195]:
optimizer.step()
print ('w1: ', w1)
print ('y_pred: ', x_data**w1 - 2 * x_data**2 + 5)

w1:  tensor([0.2917], requires_grad=True)
y_pred:  tensor([[-1.7759]], grad_fn=<AddBackward0>)


#### Вариант второй

In [196]:
# importing libraries
from torch import nn 
from torch import optim

In [200]:
x_data = Variable(torch.tensor([[2.0]]))
y_data = Variable(torch.tensor([[12.0]]))
w1 = Variable(torch.randn(1), requires_grad = True) #  creating random tensors for weights

In [201]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD([w1], lr=0.001)

In [202]:
# Training loop
for epoch in range(500):
    # 1) Forward pass: Compute predicted y by passing x to the model
    y_pred = x_data**w1 - 2 * x_data**2 + 5

    # 2) Compute and print loss
    loss = criterion(y_pred, y_data)
    if epoch % 10 == 0:
      print(f'Epoch: {epoch} | Loss: {loss.item()} | y_pred: {y_pred} ')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch: 0 | Loss: 160.9954071044922 | y_pred: tensor([[-0.6884]], grad_fn=<AddBackward0>) 
Epoch: 10 | Loss: 140.03936767578125 | y_pred: tensor([[0.1662]], grad_fn=<AddBackward0>) 
Epoch: 20 | Loss: 104.96172332763672 | y_pred: tensor([[1.7549]], grad_fn=<AddBackward0>) 
Epoch: 30 | Loss: 49.961273193359375 | y_pred: tensor([[4.9317]], grad_fn=<AddBackward0>) 
Epoch: 40 | Loss: 5.9018659591674805 | y_pred: tensor([[9.5706]], grad_fn=<AddBackward0>) 
Epoch: 50 | Loss: 0.09905177354812622 | y_pred: tensor([[11.6853]], grad_fn=<AddBackward0>) 
Epoch: 60 | Loss: 0.0008327948162332177 | y_pred: tensor([[11.9711]], grad_fn=<AddBackward0>) 
Epoch: 70 | Loss: 6.425547326216474e-06 | y_pred: tensor([[11.9975]], grad_fn=<AddBackward0>) 
Epoch: 80 | Loss: 4.980029189027846e-08 | y_pred: tensor([[11.9998]], grad_fn=<AddBackward0>) 
Epoch: 90 | Loss: 3.637978807091713e-10 | y_pred: tensor([[12.0000]], grad_fn=<AddBackward0>) 
Epoch: 100 | Loss: 2.2737367544323206e-11 | y_pred: tensor([[12.0000]], g

#### Вариант третий (оптимизация с nn.Module)

In [97]:
# importing libraries
from torch import nn 
from torch import optim

In [171]:
x_data = Variable(torch.tensor([[2.0]]))
y_data = Variable(torch.tensor([[12.0]]))

In [172]:
class FuncModel(torch.nn.Module):
    def __init__(self):
        """
        In the constructor we instantiate four parameters and assign them as
        member parameters.
        """
        super().__init__()
        self.w1 = torch.nn.Parameter(torch.randn(()))

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        y_pred = x.pow(self.w1) - 2 * x.pow(2) + 5
        return y_pred

    def string(self):
        """
        Just like any class in Python, you can also define custom method on PyTorch modules
        """
        return f'y = x**{self.w1.item()} - 2 * x**2 + 5 '

In [173]:
model = FuncModel()

In [174]:
criterion = nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

In [175]:
# Training loop
for epoch in range(500):
    # 1) Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)

    # 2) Compute and print loss
    loss = criterion(y_pred, y_data)
    if epoch % 10 == 0:
      print(f'Epoch: {epoch} | Loss: {loss.item()} | y_pred: {y_pred}')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch: 0 | Loss: 217.0359649658203 | y_pred: tensor([[-2.7321]], grad_fn=<AddBackward0>)
Epoch: 10 | Loss: 216.72572326660156 | y_pred: tensor([[-2.7216]], grad_fn=<AddBackward0>)
Epoch: 20 | Loss: 216.39064025878906 | y_pred: tensor([[-2.7102]], grad_fn=<AddBackward0>)
Epoch: 30 | Loss: 216.02761840820312 | y_pred: tensor([[-2.6979]], grad_fn=<AddBackward0>)
Epoch: 40 | Loss: 215.63302612304688 | y_pred: tensor([[-2.6844]], grad_fn=<AddBackward0>)
Epoch: 50 | Loss: 215.20257568359375 | y_pred: tensor([[-2.6698]], grad_fn=<AddBackward0>)
Epoch: 60 | Loss: 214.7312774658203 | y_pred: tensor([[-2.6537]], grad_fn=<AddBackward0>)
Epoch: 70 | Loss: 214.2130126953125 | y_pred: tensor([[-2.6360]], grad_fn=<AddBackward0>)
Epoch: 80 | Loss: 213.64053344726562 | y_pred: tensor([[-2.6164]], grad_fn=<AddBackward0>)
Epoch: 90 | Loss: 213.00486755371094 | y_pred: tensor([[-2.5947]], grad_fn=<AddBackward0>)
Epoch: 100 | Loss: 212.29522705078125 | y_pred: tensor([[-2.5704]], grad_fn=<AddBackward0>)
Ep

In [203]:
print(f'Result: {model.string()}')

Result: y = x**3.9068901538848877 - 2 * x**2 + 5 


In [204]:
# After training
x_var = Variable(torch.tensor([[4.0]]))
y_pred = model(x_var)
print("Prediction (after training)",  model(x_var).data[0][0].item())

Prediction (after training) 197.99986267089844


In [205]:
# Control test
x=4
w = 3.9068901538848877
print(f'for x = {4}, y = {x**w - 2 * x**2 + 5}')

for x = 4, y = 197.999862219272
